/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guiness_bot_external_NativeAPI */

#ifndef _Included_com_guiness_bot_external_NativeAPI
#define _Included_com_guiness_bot_external_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guiness_bot_external_NativeAPI
 * Method:    inject
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guiness_bot_external_NativeAPI_inject
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_guiness_bot_external_NativeAPI
 * Method:    injectDofus
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guiness_bot_external_NativeAPI_injectDofus
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
