/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guiness_bot_core_NativeAPI */

#ifndef _Included_com_guiness_bot_core_NativeAPI
#define _Included_com_guiness_bot_core_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guiness_bot_core_NativeAPI
 * Method:    availableProcesses
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_guiness_bot_core_NativeAPI_availableProcesses
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_guiness_bot_core_NativeAPI
 * Method:    dofusPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guiness_bot_core_NativeAPI_dofusPath
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_guiness_bot_core_NativeAPI
 * Method:    inject
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guiness_bot_core_NativeAPI_inject
        (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_guiness_bot_core_NativeAPI
 * Method:    login
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guiness_bot_core_NativeAPI_login
        (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_guiness_bot_core_NativeAPI
 * Method:    reLogin
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guiness_bot_core_NativeAPI_reLogin
        (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_guiness_bot_core_NativeAPI
 * Method:    patchProxyPort
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guiness_bot_core_NativeAPI_patchProxyPort
        (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
